name: CI

on: [create, pull_request, push]

env:
  IMAGE_ID: ${{ github.repository }}

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.5
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@1.1.0
      with:
        scandir: './src'
  semantic-release:
    if: github.event_name != 'pull_request'
    name: Semantic Release
    runs-on: ubuntu-latest
    needs: shellcheck
    steps:
      - name: Checkout
        uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # renovate: tag=v2.3.5
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@767cc0b0cd610ffb1ffee1b36a9b39120adc5f80 # renovate: tag=v2.6.0
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
